From the wiki

`--qubo`: where supported, produce output files in QUBO rather than Ising format

In [1]:
import dimod
from dwave.samplers import SimulatedAnnealingSampler

Same coefficients but different type of problem

In [2]:
linear = {'A': 1, 'B': 1, 'C': 1, 'D': 1, 'E': 1, 'F': 1}
quadratic = {('B', 'C'): 2, ('B', 'F'): 2, ('C', 'A'): 2, ('D', 'A'): 2, ('E', 'D'): 2, ('E', 'F'): 2, ('F', 'A'): 2}
bqm = dimod.BinaryQuadraticModel(linear, quadratic, 0, dimod.BINARY)

In [3]:
sampler = SimulatedAnnealingSampler()
result = sampler.sample(bqm, num_reads=1000, chain_strength=4.0)

wrong results

In [4]:
print(result.aggregate())

   A  B  C  D  E  F energy num_oc.
0  0  0  0  0  0  0    0.0     993
1  0  0  0  0  0  1    1.0       3
2  0  0  1  0  0  0    1.0       2
3  0  0  0  0  1  0    1.0       1
4  0  0  0  1  0  0    1.0       1
['BINARY', 5 rows, 1000 samples, 6 variables]


In [5]:
import numpy as np

Matrix generated by:

`qmasm --format="numpy" -o="matrix_qubo.npz" --solver="sim_anneal"  --qubo MVC.qmasm`

In [10]:
data = np.load("matrix_qubo.npz")
print(data)
print(data['qubo'])

NpzFile 'matrix_qubo.npz' with keys: qubo, lvars, syms
[[-10.   0.   8.   8.   0.   8.]
 [  0.  -6.   8.   0.   0.   8.]
 [  0.   0.  -6.   0.   0.   0.]
 [  0.   0.   0.  -6.   8.   0.]
 [  0.   0.   0.   0.  -6.   8.]
 [  0.   0.   0.   0.   0. -10.]]


Matrix generated by:

`> qmasm --format="numpy" -o="matrix_ising.npz" --solver="sim_anneal"   MVC.qmasm `

In [11]:
data = np.load("matrix_ising.npz")
print(data)
print(data['qubo'])

NpzFile 'matrix_ising.npz' with keys: qubo, lvars, syms
[[-10.   0.   8.   8.   0.   8.]
 [  0.  -6.   8.   0.   0.   8.]
 [  0.   0.  -6.   0.   0.   0.]
 [  0.   0.   0.  -6.   8.   0.]
 [  0.   0.   0.   0.  -6.   8.]
 [  0.   0.   0.   0.   0. -10.]]
